GET http://localhost:3000/api/storage
Content-Type: application/json

{

}

###
// 복사
POST http://localhost:3000/api/storage
Content-Type: application/json

{
    "ids":[5]
}

###

DELETE http://localhost:3000/api/storage
Content-Type: application/json

{
    "ids": [4,5]
}

###

GET http://localhost:3000/api/storage/1
Content-Type: application/json


###

POST http://localhost:3000/api/storage/7
Content-Type: application/json

{
    "type": "file",
    "subject":"cover.jpg"
}

###

PUT http://localhost:3000/api/storage/2
Content-Type: application/json

{   
    "subject": "데스크톱"
}

###

DELETE  http://localhost:3000/api/storage/12
Content-Type: application/json

{
    
}